FROM rust:1.40

WORKDIR /usr/src
COPY . .

RUN cargo install --path auth-server/
RUN cargo install --path gateway/
RUN cargo install --path orders/
RUN cargo install --path billing/
RUN cargo install --path warehouse/
